"""empty message

Revision ID: 2c0f41cd7ad5
Revises: eccd075cf57e
Create Date: 2025-06-03 16:51:47.671445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0f41cd7ad5'
down_revision = 'eccd075cf57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('match_name', sa.String(), nullable=True),
    sa.Column('series_name', sa.String(), nullable=True),
    sa.Column('team1', sa.String(), nullable=True),
    sa.Column('team2', sa.String(), nullable=True),
    sa.Column('team1_short', sa.String(), nullable=True),
    sa.Column('team2_short', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
