"""empty message

Revision ID: 80a6456f0afd
Revises: d291110ede81
Create Date: 2025-06-11 13:17:00.982191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a6456f0afd'
down_revision = 'd291110ede81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fantasy_team', schema=None) as batch_op:
        batch_op.alter_column('team_name',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fantasy_team', schema=None) as batch_op:
        batch_op.alter_column('team_name',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
