"""empty message

Revision ID: d291110ede81
Revises: b195c969f6b4
Create Date: 2025-06-11 12:54:52.161650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd291110ede81'
down_revision = 'b195c969f6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fantasy_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fantasy_team', schema=None) as batch_op:
        batch_op.drop_column('team_name')

    # ### end Alembic commands ###
